### ISSUE TITLE
Card custom integration ( secure fields) - TypeError: Invalid attempt to destructure non-iterable instance. 

### ISSUE THREAD

**Issue by yauvavo** [Adyen/adyen-web#2459]
**Describe the bug**
When pasting a card number inside the card number field I get an error in the console and the form becomes unusable

**To Reproduce**
1. Follow the [custom integration steps](https://docs.adyen.com/payment-methods/cards/custom-card-integration)
2. Map `onFieldValid` and `onBinLookup` events
3. Paste a card number with spaces ex: `4360 0000 0100 0005` (from adyen's chrome extension in my case)
5. See the error in the console

```javascript
Uncaught (in promise) TypeError: Invalid attempt to destructure non-iterable instance. nonIterableRest.js:2 
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableRest (nonIterableRest.js:2:1)
    at _slicedToArray (slicedToArray.js:6:1)
    at k.vm [as constructor] (index.js:1:1)
    at k.q [as render] (index.js:562:1)
    at L (index.js:208:1)
    at x (children.js:141:1)
    at L (index.js:219:1)
    at x (children.js:141:1)
    at L (index.js:219:1)
```

**Expected behavior**
I would expect to be able to paste a card number with spaces without problems.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 119.0.6045.159

**Smartphone (please complete the following information):**

**Additional context**
This is an integration inside a React application

**Comment by yauvavo** [comment]
Closing due to my own fault initialising the configuration
