### ISSUE TITLE
AdyenCheckoutError is not exported error

### ISSUE THREAD

**Issue by senturkozer** [Adyen/adyen-web#2695]
**Describe the bug**
When we try to use AdyenCheckoutError class in Karma tests, we get below error:

```
    message: 'Module not found: error: Package path ./dist/types/core/errors/AdyenCheckouterror is not exported from package /app/static/node_modules/@adyen/adyen-web (see exports field in /app/static/node_modules/@adyen/adyen-web/package.json)',
    moduleId: './src/udemy/js/checkout/components/payment-method/payment-methods/adyen/adyen-common-base-payment-method.mobx-model.spec.ts',
    moduleTrace: [ [Object], [Object], [Object] ],
    details: undefined,
    stack: 'ModuleNotFounderror: Module not found: error: Package path ./dist/types/core/errors/AdyenCheckouterror is not exported from package /app/static/node_modules/@adyen/adyen-web (see exports field in /app/static/node_modules/@adyen/adyen-web/package.json)\n' +
      '  at /app/static/node_modules/webpack/lib/Compilation.js:2029:28\n' +
      '  at /app/static/node_modules/webpack/lib/NormalModuleFactory.js:817:13\n' +
```

**To Reproduce**
Write a Karma test. During run, it throws above exception.

**Expected behavior**
AdyenCheckoutError class should be exported as expected.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Browser [e.g. Chrome]
 - Version [e.g. 125]

**Comment by sponglord** [comment]
@senturkozer - Hi. Can you explain your use case for wanting to instantiate an `AdyenCheckoutError` within your tests? As opposed to just throwing your own, native, JS `Error`?

**Comment by ribeiroguilherme** [comment]
Hey @senturkozer,

I don't think we expose any `handleError` method. Are you trying to test the internal implementation details of the library? What are you trying to test in this case?

**Comment by senturkozer** [comment]
We try to test passing down correct error object to your implementation.
